//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int idBeneficiario { get; set; }
        public string telefono { get; set; }
        public string ciudad { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string rfc { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual empresa empresa { get; set; }
        public virtual Localidad Localidad { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
