//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiarios()
        {
            this.CuentasBancarias1 = new HashSet<CuentasBancarias>();
            this.Empresas = new HashSet<Empresas>();
            this.Personas = new HashSet<Personas>();
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int IdBeneficiario { get; set; }
        public string telefono { get; set; }
        public string tiudad { get; set; }
        public string direccion { get; set; }
        public string rfc { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string CuentaBancaria { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
    
        public virtual CuentasBancarias CuentasBancarias { get; set; }
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasBancarias> CuentasBancarias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empresas> Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personas> Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
