//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancariaSolicitud
    {
        public int IdCuentaBancariaSolicitud { get; set; }
        public int SolicitudIdSolicitud { get; set; }
        public int CuentaBancaria_numeroCuenta { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
        public virtual CuentaBancaria CuentaBancaria { get; set; }
    }
}
