//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancariaSolicitudSet
    {
        public int IdCuentaBancariaSolicitud { get; set; }
        public int SolicitudIdSolicitud { get; set; }
        public int CuentaBancaria_numeroCuenta { get; set; }
    
        public virtual CuentaBancariaSet CuentaBancariaSet { get; set; }
        public virtual SolicitudSet SolicitudSet { get; set; }
    }
}
