//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseModelContainer : DbContext
    {
        public DataBaseModelContainer()
            : base("name=DataBaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiario> BeneficiarioSet { get; set; }
        public virtual DbSet<Persona> PersonaSet { get; set; }
        public virtual DbSet<empresa> empresaSet { get; set; }
        public virtual DbSet<CuentaBancaria> CuentaBancariaSet { get; set; }
        public virtual DbSet<CuentaBancariaSolicitud> CuentaBancariaSolicitudSet { get; set; }
        public virtual DbSet<Solicitud> SolicitudSet { get; set; }
        public virtual DbSet<Devoluciones> DevolucionesSet { get; set; }
        public virtual DbSet<Archivo> ArchivoSet { get; set; }
        public virtual DbSet<Dictamen> DictamenSet { get; set; }
        public virtual DbSet<Empleado> EmpleadoSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Localidad> LocalidadSet { get; set; }
        public virtual DbSet<Dependencia> DependenciaSet { get; set; }
        public virtual DbSet<LocalidadDependencia> LocalidadDependenciaSet { get; set; }
        public virtual DbSet<Proyecto> ProyectoSet { get; set; }
        public virtual DbSet<PoliticaProyecto> PoliticaProyectoSet { get; set; }
        public virtual DbSet<PoliticaOtorgamiento> PoliticaOtorgamientoSet { get; set; }
        public virtual DbSet<OrdenEntrega> OrdenEntregaSet { get; set; }
        public virtual DbSet<Recurso> RecursoSet { get; set; }
    }
}
