//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependenciaLocalidad
    {
        public int IdDependenciaLocalidad { get; set; }
        public Nullable<int> IdDependencia { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        public virtual Dependencias Dependencias { get; set; }
    }
}
