//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependenciaLocalidad
    {
        public int IdDependenciaLocalidad { get; set; }
        public Nullable<int> IdDependencia { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        public virtual Dependencias Dependencias { get; set; }
    }
}
