//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionesSet
    {
        public int IdDevolucion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public int montoDeuda { get; set; }
        public int SolicitudIdSolicitud { get; set; }
    
        public virtual SolicitudSet SolicitudSet { get; set; }
    }
}
