//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionesSet
    {
        public int IdDevolucion { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaDevolucion { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public int montoDeuda { get; set; }
        public int SolicitudIdSolicitud { get; set; }
    
        public virtual SolicitudSet SolicitudSet { get; set; }
    }
}
