//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictamenSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DictamenSet()
        {
            this.SolicitudSet = new HashSet<SolicitudSet>();
        }
    
        public int IdDictamen { get; set; }
        public string estado { get; set; }
        public string comentarios { get; set; }
        public System.DateTime fecha { get; set; }
        public int EmpleadoNumeroEmpleado { get; set; }
    
        public virtual EmpleadoSet EmpleadoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudSet> SolicitudSet { get; set; }
    }
}
