//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int IdDocumento { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
    
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
