//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidencias
    {
        public int IdEvidencia { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string direccion { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
    
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
