//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalidadDependenciaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalidadDependenciaSet()
        {
            this.ProyectoSet = new HashSet<ProyectoSet>();
        }
    
        public int IdLocalidadDependencia { get; set; }
        public int LocalidadIdLocalidad { get; set; }
        public int DependenciaIdDependencia { get; set; }
    
        public virtual DependenciaSet DependenciaSet { get; set; }
        public virtual LocalidadSet LocalidadSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoSet> ProyectoSet { get; set; }
    }
}
