//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesEntrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesEntrega()
        {
            this.Proyectos = new HashSet<Proyectos>();
        }
    
        public int IdOrdenEntrega { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string lugarEntrega { get; set; }
        public Nullable<int> IdRecurso { get; set; }
        public string cantidad { get; set; }
    
        public virtual Recursos Recursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyectos> Proyectos { get; set; }
    }
}
