//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenEntregaSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenEntregaSet()
        {
            this.ProyectoSet = new HashSet<ProyectoSet>();
        }
    
        public int IdOrdenEntrega { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public string lugarEntrega { get; set; }
        public int Recurso_IdRecurso { get; set; }
    
        public virtual RecursoSet RecursoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProyectoSet> ProyectoSet { get; set; }
    }
}
