//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaProyectoSet
    {
        public int IdPoliticaProyecto { get; set; }
        public Nullable<int> ProyectoFolio { get; set; }
        public Nullable<int> PoliticaOtorgamientoIdPolitica { get; set; }
    
        public virtual PoliticaOtorgamientoSet PoliticaOtorgamientoSet { get; set; }
        public virtual ProyectoSet ProyectoSet { get; set; }
    }
}
