//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaProyectoSet
    {
        public int IdPoliticaProyecto { get; set; }
        public Nullable<int> ProyectoFolio { get; set; }
        public Nullable<int> PoliticaOtorgamientoIdPolitica { get; set; }
    
        public virtual PoliticaOtorgamientoSet PoliticaOtorgamientoSet { get; set; }
        public virtual ProyectoSet ProyectoSet { get; set; }
    }
}
