//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoPoliticaOtorgamiento
    {
        public int IdProyectoPoliticaOtorgamiento { get; set; }
        public string Folio { get; set; }
        public Nullable<int> IdPoliticaOtorgamiento { get; set; }
    
        public virtual PoliticasOtorgamiento PoliticasOtorgamiento { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
