//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoPoliticaOtorgamiento
    {
        public int IdProyectoPoliticaOtorgamiento { get; set; }
        public string Folio { get; set; }
        public Nullable<int> IdPoliticaOtorgamiento { get; set; }
    
        public virtual PoliticasOtorgamiento PoliticasOtorgamiento { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
