//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recursos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recursos()
        {
            this.OrdenesEntrega = new HashSet<OrdenesEntrega>();
        }
    
        public int IdRecurso { get; set; }
        public string nombre { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> IdOrdenEntrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesEntrega> OrdenesEntrega { get; set; }
        public virtual OrdenesEntrega OrdenesEntrega1 { get; set; }
    }
}
