//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudSet()
        {
            this.ArchivoSet = new HashSet<ArchivoSet>();
            this.BeneficiarioSet = new HashSet<BeneficiarioSet>();
            this.CuentaBancariaSolicitudSet = new HashSet<CuentaBancariaSolicitudSet>();
            this.DevolucionesSet = new HashSet<DevolucionesSet>();
        }
    
        public int IdSolicitud { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int ProyectoFolio { get; set; }
        public Nullable<int> Dictamen_IdDictamen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoSet> ArchivoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiarioSet> BeneficiarioSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancariaSolicitudSet> CuentaBancariaSolicitudSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionesSet> DevolucionesSet { get; set; }
        public virtual DictamenSet DictamenSet { get; set; }
        public virtual ProyectoSet ProyectoSet { get; set; }
    }
}
