//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes()
        {
            this.Devoluciones = new HashSet<Devoluciones>();
            this.Documentos = new HashSet<Documentos>();
            this.Evidencias = new HashSet<Evidencias>();
        }
    
        public int IdSolicitud { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> IdDictamen { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public string Folio { get; set; }
    
        public virtual Beneficiarios Beneficiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devoluciones> Devoluciones { get; set; }
        public virtual Dictamenes Dictamenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos> Documentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidencias> Evidencias { get; set; }
        public virtual Proyectos Proyectos { get; set; }
    }
}
