//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGPM_DataBAse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudSet()
        {
            this.ArchivoSet = new HashSet<ArchivoSet>();
            this.BeneficiarioSet = new HashSet<BeneficiarioSet>();
            this.CuentaBancariaSolicitudSet = new HashSet<CuentaBancariaSolicitudSet>();
            this.DevolucionesSet = new HashSet<DevolucionesSet>();
        }
    
        public int IdSolicitud { get; set; }
        public string estado { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int ProyectoFolio { get; set; }
        public Nullable<int> Dictamen_IdDictamen { get; set; }
        public Nullable<int> BeneficiarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivoSet> ArchivoSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiarioSet> BeneficiarioSet { get; set; }
        public virtual BeneficiarioSet BeneficiarioSet1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancariaSolicitudSet> CuentaBancariaSolicitudSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionesSet> DevolucionesSet { get; set; }
        public virtual DictamenSet DictamenSet { get; set; }
        public virtual ProyectoSet ProyectoSet { get; set; }
    }
}
